# Generated by Django 3.2 on 2023-06-26 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_created_dt_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
